// <auto-generated />
using System;
using GT.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GT.Data.Migrations
{
    [DbContext(typeof(TarefaContext))]
    partial class TarefaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GT.Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DateTime")
                        .HasColumnName("dataCadastro");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("DateTime")
                        .HasColumnName("dataConclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varChar(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INT")
                        .HasColumnName("prioridade");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varChar(50)")
                        .HasColumnName("titulo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INT")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id")
                        .HasName("PK_Tarefa_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IDX_Tarefa_usuarioId");

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VarChar(10)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PK_Usuario_Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("GT.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Tarefa_Usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GT.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
